<a href="https://colab.research.google.com/github/aakashkumarme/TFLEARN/blob/main/3_Fitting_the_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

heart_disease = pd.read_csv("/content/drive/MyDrive/dataset/heart-disease.csv")

X = heart_disease.drop("target",axis = 1)
y = heart_disease["target"]

from sklearn.model_selection import train_test_split
np.random.seed(42)
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size = 0.20)

from sklearn.ensemble import RandomForestClassifier
clf  = RandomForestClassifier()
clf.fit(X_train,y_train)
clf.score(X_test,y_test)

0.8524590163934426

Using two techniques for trained model to make prediction.



1.   Predict Function
2.   Predict Proba 





### Applying Predict for Classification Problem

In [2]:
X_test.head()

age  sex  cp  trestbps  chol  ...  exang  oldpeak  slope  ca  thal
179   57    1   0       150   276  ...      1      0.6      1   1     1
228   59    1   3       170   288  ...      0      0.2      1   0     3
111   57    1   2       150   126  ...      0      0.2      2   1     3
246   56    0   0       134   409  ...      1      1.9      1   2     3
60    71    0   2       110   265  ...      0      0.0      2   1     2

[5 rows x 13 columns]

In [3]:
clf.predict(X_test)

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0])

Predict Function

In [4]:
#Method 1
y_preds = clf.predict(X_test)
np.mean(y_preds == y_test) #here we are comparing the predicted value after training and the reserved testing value

0.8524590163934426

In [5]:
#Method 2
clf.score(X_test , y_test)

0.8524590163934426

In [6]:
#Method 3
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_preds)

0.8524590163934426

Preict Proba()

In [7]:
#Predict proba() returns probablities of a classification label
#here , probablity of heart disease is 0.88 and not heart disease is 0.12
clf.predict_proba(X_test[:5])

array([[0.89, 0.11],
       [0.49, 0.51],
       [0.43, 0.57],
       [0.84, 0.16],
       [0.18, 0.82]])

In [9]:
 clf.predict(X_test[:5])

array([0, 1, 1, 0, 1])

### Applying Predict for Regression Problem

In [13]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_boston
boston = load_boston()

boston_df = pd.DataFrame(boston["data"], columns = boston["feature_names"])
boston_df["target"] = pd.Series(boston["target"])
boston_df.head()

X = boston_df.drop("target" , axis=1)
y = boston_df["target"]

In [18]:
from sklearn.model_selection import train_test_split
np.random.seed(42)
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size = 0.20)

from sklearn.ensemble import RandomForestRegressor
clf  = RandomForestRegressor()
clf.fit(X_train,y_train)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=100, n_jobs=None, oob_score=False,
                      random_state=None, verbose=0, warm_start=False)

In [15]:
y_preds = clf.predict(X_test)

In [16]:
y_preds[:10] #prediction

array([23.002, 30.826, 16.734, 23.467, 16.853, 21.725, 19.232, 15.239,
       21.067, 20.738])

In [17]:
np.array(y_test[:10]) #actual

array([23.6, 32.4, 13.6, 22.8, 16.1, 20. , 17.8, 14. , 19.6, 16.8])

In [19]:
#comapre "predictions" to "actual"

from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test,y_preds)

2.1226372549019623